# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise32"

  $script = <<EOS
if [[ "" == `which carton` ]]; then
    apt-get install make

    cd /tmp
    wget http://xrl.us/cpanm
    chmod +x cpanm
    ./cpanm install Carton
fi
EOS

  config.vm.provision "shell", inline: $script
end
